# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmm', '0003_auto_20180525_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfeature',
            name='function',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testfeature',
            name='group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
