# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmm', '0004_auto_20180525_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfeature',
            name='dependency',
        ),
        migrations.AddField(
            model_name='testfeature',
            name='dependency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
