# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmm', '0006_auto_20180525_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfeature',
            old_name='selection_name',
            new_name='feature_name',
        ),
    ]
