# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmm', '0009_auto_20180531_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestDependency',
            new_name='TestDependency2',
        ),
    ]
